name: Update WordInfo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 0

    - name: Update WordInfo\Gender\*
      shell: powershell # Forces the usage of PowerShell Desktop
      run: .\update-wordinfo-gender.ps1

    - name: Update WordInfo\decline.txt
      shell: powershell
      run: .\update-wordinfo-decline.ps1

    - name: Update WordInfo\plural.txt
      shell: powershell
      run: .\update-wordinfo-plural.ps1

    - name: Commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -a -m "Update WordInfo"
        git push
